#!/usr/bin/env bash
# Entrypoint shim for the postgres container when WAL archiving is enabled.
# Maps BACKUP_* -> PGBACKREST_* once, then hands off to the stock
# docker-entrypoint.sh unchanged.
#
# WHY THIS EXISTS, AND WHY IT IS AN ENTRYPOINT RATHER THAN AN archive_command
# WRAPPER
# --------------------------------------------------------------------------
# Two different Postgres child processes shell out to pgBackRest:
#
#   archive_command  — pushes each WAL segment  (normal running)
#   restore_command  — fetches each WAL segment (during recovery)
#
# Both inherit the postmaster's environment, and both need the S3 credentials
# and the repo cipher passphrase. restore_command is GENERATED BY pgBackRest
# itself into postgresql.auto.conf at restore time, so we do not get to wrap it
# — pgBackRest's own --cmd option can override the binary it embeds, but its
# docs say "wrapping the pgBackRest command may cause unpredictable behavior and
# is not recommended".
#
# Exporting the variables once here, before the postmaster starts, means every
# child inherits them and BOTH commands are the plain documented form. It also
# keeps the BACKUP_* -> PGBACKREST_* mapping in exactly one place (lib.sh),
# shared with the backup container, so the two cannot drift apart and leave one
# side rotated and the other not.
#
# Found the hard way: without this, backups succeed, archiving succeeds, and the
# RESTORE fails with "[037]: archive-get command requires option:
# repo1-cipher-pass" — i.e. you discover it the day you need the backup.
set -euo pipefail

# Only map when a destination is actually configured. This image is also usable
# without backups (archiving off), and it must not refuse to boot then.
if [ -n "${BACKUP_S3_ENDPOINT:-}" ]; then
  LOG_TAG=postgres-entrypoint
  # shellcheck source=lib.sh
  . /opt/backup/lib.sh
  export_pgbackrest_env >/dev/null
fi

exec /usr/local/bin/docker-entrypoint.sh "$@"
