export enum ConfigEnum {
  DATABASE_URL = 'DATABASE_URL',
  REDIS_URL = 'REDIS_URL',
  SECRET = 'SECRET',
}

export enum LogEnum {
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_ON = 'LOG_ON',
  TIMESTAMP = 'TIMESTAMP',
  HTTP_LOG_ON = 'HTTP_LOG_ON',
  SLOW_REQUEST_MS = 'SLOW_REQUEST_MS',
  BUSINESS_LOG_ON = 'BUSINESS_LOG_ON',
  EXTERNAL_LOG_ON = 'EXTERNAL_LOG_ON',
  RATE_LIMIT_LOG_ON = 'RATE_LIMIT_LOG_ON',
}
