#!/usr/bin/env bash
# Derives the postgres_exporter / redis_exporter connection settings from
# .env.production and writes them to monitoring/.env.exporters, which the
# production monitoring overlay loads via `env_file`.
#
#   bash monitoring/sync-exporter-env.sh
#
# Run it once during setup, and again after rotating DB_PASSWORD or REDIS_URL —
# otherwise the exporters keep dialing with stale credentials and their targets
# go DOWN while the dashboard looks installed.
#
# Why a script rather than "copy the password":
#   - it is the SAME secret as the app's, so hand-copying creates a second copy
#     that silently drifts on the next rotation;
#   - DATABASE_URL carries Prisma's `?schema=public`, which libpq rejects
#     outright ("invalid URI query parameter"). Pasting it verbatim produces an
#     exporter that starts fine and fails every scrape.
#
# NOTE: unlike sync-metrics-token.sh this file is read by the docker compose CLI
# (env_file), not mounted into a container, so it needs no uid-65534 ownership
# dance — it only has to be readable by the deploying user.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE="${ENV_FILE:-.env.production}"
OUT_FILE="${OUT_FILE:-monitoring/.env.exporters}"

if [ ! -f "$ENV_FILE" ]; then
  echo "❌ $ENV_FILE not found. Run deploy/gen-env.sh first (see DEPLOY.md §4)." >&2
  exit 1
fi

# Last assignment wins, matching dotenv. Tolerates optional quotes; strips a
# trailing CR so a CRLF-edited .env.production cannot inject one.
read_env() {
  local value
  value="$(sed -n "s/^$1=//p" "$ENV_FILE" | tail -n 1 | tr -d '\r')"
  value="${value%\"}"; value="${value#\"}"
  value="${value%\'}"; value="${value#\'}"
  printf '%s' "$value"
}

database_url="$(read_env DATABASE_URL)"
redis_url="$(read_env REDIS_URL)"

if [ -z "$database_url" ]; then
  echo "❌ DATABASE_URL is empty or missing in $ENV_FILE." >&2
  exit 1
fi
case "$database_url" in
  *__DB_PASSWORD__*)
    echo "❌ DATABASE_URL still contains the __DB_PASSWORD__ placeholder from" >&2
    echo "   .env.production.example. Run deploy/gen-env.sh." >&2
    exit 1
    ;;
esac

# Strip Prisma's query string (?schema=public) — libpq rejects the `schema`
# parameter — and pin sslmode explicitly. The exporter reaches Postgres over the
# private compose network, never the public internet.
pg_dsn="${database_url%%\?*}?sslmode=disable"

if [ -z "$redis_url" ]; then
  echo "❌ REDIS_URL is empty or missing in $ENV_FILE." >&2
  echo "   This deployment has no Redis, so redis-exporter would be a target" >&2
  echo "   that is DOWN forever — which just teaches everyone to ignore red." >&2
  echo "   Remove the redis-exporter service and its scrape job instead." >&2
  exit 1
fi
case "$redis_url" in
  *__REDIS_PASSWORD__*)
    echo "❌ REDIS_URL still contains the __REDIS_PASSWORD__ placeholder." >&2
    exit 1
    ;;
esac

umask 077
temp_file="$(mktemp "$(dirname "$OUT_FILE")/.$(basename "$OUT_FILE").tmp.XXXXXX")"
trap 'rm -f "$temp_file"' EXIT

cat > "$temp_file" <<EOF
# GENERATED by monitoring/sync-exporter-env.sh — do not edit, do not commit.
# Regenerate after rotating DB_PASSWORD or REDIS_URL.
#
# redis_exporter parses the full redis:// URI itself, including URL-encoded
# credentials — deliberately not split into REDIS_USER/REDIS_PASSWORD here,
# which would mean re-implementing percent-decoding in shell.
DATA_SOURCE_NAME=$pg_dsn
REDIS_ADDR=$redis_url
EOF

chmod 600 "$temp_file"
mv -f "$temp_file" "$OUT_FILE"
trap - EXIT

echo "✅ wrote $OUT_FILE (0600)"
echo "   Recreate the exporters to pick it up:"
echo "     docker compose -f monitoring/docker-compose.yml -f monitoring/docker-compose.prod.yml up -d postgres-exporter redis-exporter"
