ALTER TYPE "CirclePostStatus" ADD VALUE IF NOT EXISTS 'ENDED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CIRCLE_POST_AUTO_ENDED';

ALTER TABLE "CirclePost"
ADD COLUMN IF NOT EXISTS "endedAt" TIMESTAMP(3);
